
spring:
  application:
    name: gateway
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: system-api # 路由的编号
          uri: grayLb://system-api
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/system-api/**
#          filters:
#            - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
#        - id: system-app-api # 路由的编号
#          uri: grayLb://system-server
#          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
#            - Path=/app-api/system/**
#          filters:
#            - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
#    routes:
#      - name: system-server
#        service-name: system-server
#        url: /admin-api/system/v3/api-docs
#      - name: infra-server
#        service-name: infra-server
#        url: /admin-api/infra/v3/api-docs
#      - name: bpm-server
#        service-name: bpm-server
#        url: /admin-api/bpm/v3/api-docs

